// Code generated by protoc-gen-go. DO NOT EDIT.
// source: diagnosticreport.proto

package diagnosticreport

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca77d5be3751963, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type FileLength struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Length               int32    `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileLength) Reset()         { *m = FileLength{} }
func (m *FileLength) String() string { return proto.CompactTextString(m) }
func (*FileLength) ProtoMessage()    {}
func (*FileLength) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca77d5be3751963, []int{1}
}

func (m *FileLength) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileLength.Unmarshal(m, b)
}
func (m *FileLength) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileLength.Marshal(b, m, deterministic)
}
func (m *FileLength) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileLength.Merge(m, src)
}
func (m *FileLength) XXX_Size() int {
	return xxx_messageInfo_FileLength.Size(m)
}
func (m *FileLength) XXX_DiscardUnknown() {
	xxx_messageInfo_FileLength.DiscardUnknown(m)
}

var xxx_messageInfo_FileLength proto.InternalMessageInfo

func (m *FileLength) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileLength) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type CommandOutput struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Output               string   `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	StatusCode           int32    `protobuf:"varint,3,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandOutput) Reset()         { *m = CommandOutput{} }
func (m *CommandOutput) String() string { return proto.CompactTextString(m) }
func (*CommandOutput) ProtoMessage()    {}
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca77d5be3751963, []int{2}
}

func (m *CommandOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandOutput.Unmarshal(m, b)
}
func (m *CommandOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandOutput.Marshal(b, m, deterministic)
}
func (m *CommandOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandOutput.Merge(m, src)
}
func (m *CommandOutput) XXX_Size() int {
	return xxx_messageInfo_CommandOutput.Size(m)
}
func (m *CommandOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CommandOutput proto.InternalMessageInfo

func (m *CommandOutput) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *CommandOutput) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *CommandOutput) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

type UnknownPair struct {
	Unknown1             string   `protobuf:"bytes,1,opt,name=unknown1,proto3" json:"unknown1,omitempty"`
	Unknown2             string   `protobuf:"bytes,2,opt,name=unknown2,proto3" json:"unknown2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnknownPair) Reset()         { *m = UnknownPair{} }
func (m *UnknownPair) String() string { return proto.CompactTextString(m) }
func (*UnknownPair) ProtoMessage()    {}
func (*UnknownPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca77d5be3751963, []int{3}
}

func (m *UnknownPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnknownPair.Unmarshal(m, b)
}
func (m *UnknownPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnknownPair.Marshal(b, m, deterministic)
}
func (m *UnknownPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnknownPair.Merge(m, src)
}
func (m *UnknownPair) XXX_Size() int {
	return xxx_messageInfo_UnknownPair.Size(m)
}
func (m *UnknownPair) XXX_DiscardUnknown() {
	xxx_messageInfo_UnknownPair.DiscardUnknown(m)
}

var xxx_messageInfo_UnknownPair proto.InternalMessageInfo

func (m *UnknownPair) GetUnknown1() string {
	if m != nil {
		return m.Unknown1
	}
	return ""
}

func (m *UnknownPair) GetUnknown2() string {
	if m != nil {
		return m.Unknown2
	}
	return ""
}

type DiagnosticReport struct {
	Version              string           `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Files                []*File          `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	StormVersion         string           `protobuf:"bytes,3,opt,name=stormVersion,proto3" json:"stormVersion,omitempty"`
	WhirlwindVersion     string           `protobuf:"bytes,4,opt,name=whirlwindVersion,proto3" json:"whirlwindVersion,omitempty"`
	NetworkConfig        string           `protobuf:"bytes,5,opt,name=networkConfig,proto3" json:"networkConfig,omitempty"`
	FileLengths          []*FileLength    `protobuf:"bytes,7,rep,name=fileLengths,proto3" json:"fileLengths,omitempty"`
	WanInfo              string           `protobuf:"bytes,8,opt,name=wanInfo,proto3" json:"wanInfo,omitempty"`
	CommandOutputs       []*CommandOutput `protobuf:"bytes,9,rep,name=commandOutputs,proto3" json:"commandOutputs,omitempty"`
	InfoJSON             string           `protobuf:"bytes,16,opt,name=infoJSON,proto3" json:"infoJSON,omitempty"`
	Unknown1             int32            `protobuf:"varint,11,opt,name=unknown1,proto3" json:"unknown1,omitempty"`
	UnknownPairs         []*UnknownPair   `protobuf:"bytes,12,rep,name=unknownPairs,proto3" json:"unknownPairs,omitempty"`
	UnixTime             int32            `protobuf:"varint,13,opt,name=unixTime,proto3" json:"unixTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DiagnosticReport) Reset()         { *m = DiagnosticReport{} }
func (m *DiagnosticReport) String() string { return proto.CompactTextString(m) }
func (*DiagnosticReport) ProtoMessage()    {}
func (*DiagnosticReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca77d5be3751963, []int{4}
}

func (m *DiagnosticReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiagnosticReport.Unmarshal(m, b)
}
func (m *DiagnosticReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiagnosticReport.Marshal(b, m, deterministic)
}
func (m *DiagnosticReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiagnosticReport.Merge(m, src)
}
func (m *DiagnosticReport) XXX_Size() int {
	return xxx_messageInfo_DiagnosticReport.Size(m)
}
func (m *DiagnosticReport) XXX_DiscardUnknown() {
	xxx_messageInfo_DiagnosticReport.DiscardUnknown(m)
}

var xxx_messageInfo_DiagnosticReport proto.InternalMessageInfo

func (m *DiagnosticReport) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DiagnosticReport) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *DiagnosticReport) GetStormVersion() string {
	if m != nil {
		return m.StormVersion
	}
	return ""
}

func (m *DiagnosticReport) GetWhirlwindVersion() string {
	if m != nil {
		return m.WhirlwindVersion
	}
	return ""
}

func (m *DiagnosticReport) GetNetworkConfig() string {
	if m != nil {
		return m.NetworkConfig
	}
	return ""
}

func (m *DiagnosticReport) GetFileLengths() []*FileLength {
	if m != nil {
		return m.FileLengths
	}
	return nil
}

func (m *DiagnosticReport) GetWanInfo() string {
	if m != nil {
		return m.WanInfo
	}
	return ""
}

func (m *DiagnosticReport) GetCommandOutputs() []*CommandOutput {
	if m != nil {
		return m.CommandOutputs
	}
	return nil
}

func (m *DiagnosticReport) GetInfoJSON() string {
	if m != nil {
		return m.InfoJSON
	}
	return ""
}

func (m *DiagnosticReport) GetUnknown1() int32 {
	if m != nil {
		return m.Unknown1
	}
	return 0
}

func (m *DiagnosticReport) GetUnknownPairs() []*UnknownPair {
	if m != nil {
		return m.UnknownPairs
	}
	return nil
}

func (m *DiagnosticReport) GetUnixTime() int32 {
	if m != nil {
		return m.UnixTime
	}
	return 0
}

func init() {
	proto.RegisterType((*File)(nil), "diagnosticreport.File")
	proto.RegisterType((*FileLength)(nil), "diagnosticreport.FileLength")
	proto.RegisterType((*CommandOutput)(nil), "diagnosticreport.CommandOutput")
	proto.RegisterType((*UnknownPair)(nil), "diagnosticreport.UnknownPair")
	proto.RegisterType((*DiagnosticReport)(nil), "diagnosticreport.DiagnosticReport")
}

func init() { proto.RegisterFile("diagnosticreport.proto", fileDescriptor_cca77d5be3751963) }

var fileDescriptor_cca77d5be3751963 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0xd7, 0x74, 0x5b, 0x6f, 0x52, 0x14, 0xf9, 0xa1, 0xb2, 0x10, 0x1f, 0x55, 0xc4, 0x43,
	0x85, 0xd0, 0x24, 0x06, 0x0f, 0x3c, 0x21, 0xa1, 0xf2, 0x21, 0x10, 0x62, 0xc8, 0x7c, 0xbc, 0x87,
	0xc6, 0x69, 0xad, 0x25, 0x76, 0x64, 0x3b, 0x84, 0xdf, 0xc0, 0xaf, 0x9e, 0x72, 0xed, 0x64, 0xc9,
	0xb2, 0xb7, 0x9e, 0xe3, 0x73, 0xce, 0xbd, 0xf6, 0x69, 0x60, 0x9d, 0x89, 0xf4, 0x20, 0x95, 0xb1,
	0x62, 0xaf, 0x79, 0xa5, 0xb4, 0xbd, 0xa8, 0xb4, 0xb2, 0x8a, 0xc4, 0x77, 0xf9, 0xe4, 0x35, 0x04,
	0x1f, 0x45, 0xc1, 0x09, 0x81, 0xa0, 0x4a, 0xed, 0x91, 0xce, 0x36, 0xb3, 0xed, 0x92, 0xe1, 0x6f,
	0x42, 0xe1, 0x6c, 0xaf, 0xa4, 0xe5, 0xd2, 0xd2, 0x93, 0xcd, 0x6c, 0x1b, 0xb1, 0x0e, 0x26, 0x6f,
	0x00, 0x5a, 0xd7, 0x57, 0x2e, 0x0f, 0xf6, 0x78, 0xaf, 0x77, 0x0d, 0xa7, 0x05, 0x9e, 0xa2, 0x75,
	0xc1, 0x3c, 0x4a, 0x52, 0x58, 0xed, 0x54, 0x59, 0xa6, 0x32, 0xbb, 0xaa, 0x6d, 0x55, 0x5b, 0x37,
	0x04, 0x09, 0xef, 0xef, 0x60, 0x1b, 0xa1, 0x50, 0x83, 0x11, 0x4b, 0xe6, 0x11, 0x79, 0x02, 0x60,
	0x6c, 0x6a, 0x6b, 0xb3, 0x53, 0x19, 0xa7, 0x73, 0x8c, 0x1f, 0x30, 0xc9, 0x07, 0x08, 0x7f, 0xc9,
	0x6b, 0xa9, 0x1a, 0xf9, 0x3d, 0x15, 0x9a, 0x3c, 0x84, 0xf3, 0xda, 0xc1, 0x97, 0x7e, 0x42, 0x8f,
	0x07, 0x67, 0x97, 0x7e, 0x48, 0x8f, 0x93, 0xff, 0x01, 0xc4, 0xef, 0xfb, 0xe7, 0x62, 0xf8, 0x5c,
	0xed, 0xb6, 0x7f, 0xb9, 0x36, 0x42, 0xc9, 0x6e, 0x5b, 0x0f, 0xc9, 0x0b, 0x58, 0xe4, 0xa2, 0xe0,
	0x86, 0x9e, 0x6c, 0xe6, 0xdb, 0xf0, 0x72, 0x7d, 0x31, 0xa9, 0xa0, 0x7d, 0x31, 0xe6, 0x44, 0x24,
	0x81, 0xc8, 0x58, 0xa5, 0xcb, 0xdf, 0x3e, 0x6c, 0x8e, 0x61, 0x23, 0x8e, 0x3c, 0x87, 0xb8, 0x39,
	0x0a, 0x5d, 0x34, 0x42, 0x66, 0x9d, 0x2e, 0x40, 0xdd, 0x84, 0x27, 0xcf, 0x60, 0x25, 0xb9, 0x6d,
	0x94, 0xbe, 0xde, 0x29, 0x99, 0x8b, 0x03, 0x5d, 0xa0, 0x70, 0x4c, 0x92, 0xb7, 0x10, 0xe6, 0x7d,
	0x6d, 0x86, 0x9e, 0xe1, 0xa6, 0x8f, 0xee, 0xdf, 0xd4, 0x89, 0xd8, 0xd0, 0xd0, 0xde, 0xbe, 0x49,
	0xe5, 0x67, 0x99, 0x2b, 0x7a, 0xee, 0x6e, 0xef, 0x21, 0xf9, 0x04, 0x0f, 0xf6, 0xc3, 0x5a, 0x0d,
	0x5d, 0x62, 0xf8, 0xd3, 0x69, 0xf8, 0xa8, 0x7e, 0x76, 0xc7, 0xd6, 0x36, 0x22, 0x64, 0xae, 0xbe,
	0xfc, 0xb8, 0xfa, 0x46, 0x63, 0xd7, 0x48, 0x87, 0x47, 0x4d, 0x86, 0x58, 0xfb, 0x6d, 0x93, 0xef,
	0x20, 0xaa, 0x6f, 0x4b, 0x37, 0x34, 0xc2, 0xf1, 0x8f, 0xa7, 0xe3, 0x07, 0x7f, 0x0d, 0x36, 0xb2,
	0xb8, 0x78, 0xf1, 0xef, 0xa7, 0x28, 0x39, 0x5d, 0x75, 0xf1, 0x0e, 0xff, 0x39, 0xc5, 0xef, 0xe7,
	0xd5, 0x4d, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x11, 0x18, 0x25, 0x59, 0x03, 0x00, 0x00,
}
